Feature | Sort Organisation Table
IATI/validator-web pull request #131
Opened 2022-10-11 15:16 UTC by ThatcherK

2022-10-14 07:26 UTC, edwinmp requested changes
For validation status, a range doesn't make sense ... i.e. Critical - Success. You want to give users an option to decide what they want to see first ... so every option has to be represented. Also, if it's not a hustle, make sure that only available file statuses are shown. Lastly, don't mix up cases ... Upper, lower - stick to one - prefer to make every first letter upper case, except for connecting words like `in` or `that` (whatever they're called in english)  i.e `Validation Status: Critical` ... notice the use of spaces.

As for the counters - please change the label text for the error counts to be in the matching colour for that error ... i.e Critical is purple. Only the labels, not the number.

On mobile, have each the feedback and the sort dropdown each on its own row.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/5672438/195787493-9e0a2af0-0d92-42b1-ab4b-8ca80923d3b7.png">

2022-10-17 07:49 UTC, edwinmp commented
As I mentioned, ONLY on mobile
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/5672438/196114485-739ae82a-7216-4ee6-ac0b-3a43b9a847e6.png">

Again, just on mobile, add padding or a margin between the two items. `mt-2` should do.

Replace `Alphabetical` with `A - Z` and `Z - A`
Replace `New-Old` with `Newest`, `Old-New` with `Oldest`

The default sorting criteria should be showing by default. You'll need to add a label to the field that clearly identifies its purpose as a sorting dropdown.

Change the drop-down colours to IATI colours.

2022-10-17 16:07 UTC, ThatcherK commented
@edwinmp  this is ready for another review

2022-10-17 17:14 UTC, edwinmp requested changes

2022-10-17 17:14 UTC, edwinmp commented on src/pages/OrganisationPage.vue
> +</style>
What if I need this used else where (very likely), do I have to copy paste all this for every usage?
Create a component that embodies this customisation so we can use it throughout https://vuejs.org/guide/components/attrs.html#nested-component-inheritance

2022-10-17 17:14 UTC, edwinmp commented on src/utils/document.js
> +    // console.log(sortDirection);
Remove

2022-10-17 17:14 UTC, edwinmp commented on src/utils/document.js
> +export const processedTableDocumentFields = (documents, sortKey, sortDirection) => {
Generic naming ... Don't need to know this is being used on a table. If it's a sort function, name it so. Current naming tells me that this function is returning processed table document fields.

2022-10-18 07:06 UTC, edwinmp commented
Fix the conflicts.

2022-10-18 07:10 UTC, ThatcherK commented
conflicts fixed

2022-10-18 07:22 UTC, merged